# NumPy notebook


## Introduction
NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers.

## Installation

In [1]:
import numpy
numpy.__version__ # check version

'1.14.2'

In [2]:
import numpy as np # alias convention

In [3]:
# Default configuration for using auto completion with tab key
%config IPCompleter.greedy=True

In [10]:
# Information about NumPy package
np?

In [9]:
# np.<TAB>
# list of all functions and attributes in NumPy
np.*?


## Python Data Types explanation
To get more information about how python data type works follow this [link](https://github.com/jakevdp/PythonDataScienceHandbook/blob/599aa0fe3f882c0001670e676e5a8d43b92c35fc/notebooks/02.01-Understanding-Data-Types.ipynb)

It's important to know that NumPy array is an Python object which only one type of object is associated with and contains a pointer to one contiguous block of data. Otherwise Python List is a list of Python object references which means that Python keep information of each object (information structure) in list and hence a Python list can contain  data of any desired type.

NumPy choose this way to manage, manipulate and store data efficiently. 

Note that Python proposes since 3.3 version an array module to create dense arrays of a uniform type. Much more useful, however, is the *ndarray* object of the NumPy package

## Creating Arrays from Python Lists

In [11]:
import numpy as np

In [13]:
# integer array:
# so array with same data type
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [17]:
# Ho ! Array with integer and floating point values ? 
# NumPy will upcast if possible
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [18]:
# Manually specify data type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [19]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.

In [20]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create an array of ten values evenly spaced between 0 and 1
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.68218758, 0.60624   , 0.11290186],
       [0.85467699, 0.9896135 , 0.98983273],
       [0.95218315, 0.8150115 , 0.89617766]])

In [30]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.7677465 ,  0.69615752, -0.86811856],
       [-0.35769419, -1.06830003,  0.97608276],
       [-1.42157588, -0.40031958, -0.4354921 ]])

In [31]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 9, 9],
       [4, 0, 6],
       [6, 6, 2]])

In [32]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [34]:
# NumPy Standard Data Types
np.zeros(10, dtype='int16') # using string
np.zeros(10, dtype=np.int16) # using NumPy object

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)