# NumPy notebook


## Introduction
NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers.

## Installation

In [1]:
import numpy
numpy.__version__ # check version

'1.14.2'

In [2]:
import numpy as np # alias convention

In [3]:
# Default configuration for using auto completion with tab key
%config IPCompleter.greedy=True

In [10]:
# Information about NumPy package
np?

In [9]:
# np.<TAB>
# list of all functions and attributes in NumPy
np.*?


## Python Data Types explanation
To get more information about how python data type works follow this [link](https://github.com/jakevdp/PythonDataScienceHandbook/blob/599aa0fe3f882c0001670e676e5a8d43b92c35fc/notebooks/02.01-Understanding-Data-Types.ipynb)

It's important to know that NumPy array is an Python object which only one type of object is associated with and contains a pointer to one contiguous block of data. Otherwise Python List is a list of Python object references which means that Python keep information of each object (information structure) in list and hence a Python list can contain  data of any desired type.

NumPy choose this way to manage, manipulate and store data efficiently. 

Note that Python proposes since 3.3 version an array module to create dense arrays of a uniform type. Much more useful, however, is the *ndarray* object of the NumPy package

## Creating Arrays from Python Lists

In [11]:
import numpy as np

In [13]:
# integer array:
# so array with same data type
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [17]:
# Ho ! Array with integer and floating point values ? 
# NumPy will upcast if possible
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [18]:
# Manually specify data type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [19]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.

In [20]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create an array of ten values evenly spaced between 0 and 1
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.68218758, 0.60624   , 0.11290186],
       [0.85467699, 0.9896135 , 0.98983273],
       [0.95218315, 0.8150115 , 0.89617766]])

In [30]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.7677465 ,  0.69615752, -0.86811856],
       [-0.35769419, -1.06830003,  0.97608276],
       [-1.42157588, -0.40031958, -0.4354921 ]])

In [31]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 9, 9],
       [4, 0, 6],
       [6, 6, 2]])

In [32]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [34]:
# NumPy Standard Data Types
np.zeros(10, dtype='int16') # using string
np.zeros(10, dtype=np.int16) # using NumPy object

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## Basic of NumPy Arrays

- Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
- Indexing of arrays: Getting and setting the value of individual array elements
- Slicing of arrays: Getting and setting smaller subarrays within a larger array
- Reshaping of arrays: Changing the shape of a given array
- Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many


### Attributes

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
# x3 Array attributes
print("x3 ndim: ", x3.ndim) # number of dimensions
print("x3 shape:", x3.shape) # the size of each dimension
print("x3 size: ", x3.size) # total sie of the array
print("x3 dtype:", x3.dtype) # data type
print("x3 itemsize:", x3.itemsize, "bytes") # size in byte of each element
print("x3 nbytes:", x3.nbytes, "bytes") # size of array (size * itemsize)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype: int64
x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


### Indexing

In [10]:
# Array Indexing
print(x1)
print(x1[0]) # print first element of array
print(x1[-1]) # index from the end of the array
print("print x1[-2]: ", x1[-2])

[5 0 3 3 7 9]
5
9
print x1[-2]:  7


In [13]:
# In multi-dimensional array:
print(x2)
print(x2[0, 1]) # row then column
print(x2[-1, -1]) # end of diagonale

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
5
7


In [14]:
# Update value element
x2[0, 0] = 7
print(x2)

[[7 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [15]:
# cannot set value which does not have same dtype
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

### Slicing

```
x[start:stop:step]
```

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [22]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [23]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [24]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [25]:
x[::3]  # every other element

array([0, 3, 6, 9])

In [26]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [27]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

## N-dimensional arrays

In [29]:
x2

array([[7, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [30]:
x2[:2, :3]  # two rows, three columns

array([[7, 5, 2],
       [7, 6, 8]])

In [34]:
x2[:3, ::2]  # all rows, every other column

array([[7, 2],
       [7, 8],
       [1, 7]])

In [39]:
x2[::-1, ::-1] # subarray dimensions can even be reversed together

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 7]])

In [42]:
print(x2[:, 0])  # first column of x2


[7 7 1]


In [43]:
print(x2[0, :])  # first row of x2

[7 5 2 4]


In [44]:
print(x2[0])  # equivalent to x2[0, :]

[7 5 2 4]


In [45]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[7 5]
 [7 6]]


In [46]:
x2_sub[0, 0] = 99 # update this new sub array
print(x2_sub)

[[99  5]
 [ 7  6]]


In [48]:
print(x2) # also change the original array!

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [49]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [50]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [51]:
print(x2) # does not change array

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping

In [52]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(grid.reshape((1,9)))

[[1 2 3 4 5 6 7 8 9]]


In [54]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [55]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [56]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [57]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Concatenation and Splitting

In [58]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [59]:
z = [99, 99, 99]
print(np.concatenate([x, y, z])) # more than 2 arrays

[ 1  2  3  3  2  1 99 99 99]


In [60]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [64]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[9, 8, 7, 9, 8, 7],
       [6, 5, 4, 6, 5, 4]])

In [65]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [67]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

# Similary, np.dstack will stack arrays along the third axis.

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [68]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [70]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [72]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [92]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [94]:
# Similarly, np.dsplit will split arrays along the third axis.

In [99]:
a1, a2, a3, a4 = np.vsplit(grid, [1, 2, 3])
print(a1)
print(a2)
print(a3)
print(a4)
print(a[0])

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


NameError: name 'a' is not defined

## Computation on NumPy Arrays: Universal Functions